### ISSUE TITLE
merge choo-log into choo-devtools

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/discuss#2]
Right now we have `choo-log` for development logging, and `choo-devtools` as a set of commands for introspection. They seem to compliment each other quite well, and it's not uncommon to install both.

I was thinking it might make sense to merge the two repos as `choo-devtools` – that way people only need to use a single package during development, and we get to redefine what people's notion of what framework-specific devtools can look like.

@choojs/trainspotters thoughts?

**Comment by ungoldman** [comment]
Ran into an issue today that might be a good reason to keep them separate: https://github.com/hypermodules/hyperamp/issues/237

I would say if you really want a single module that has both choo-devtools & choo-log, make a third module 😉

**Comment by yoshuawuyts** [comment]
@ungoldman Hmm, that seems like a bug with `choo-devtools` itself.
Regardless if it's merged or not, it should under no circumstance make your
app unresponsive. Cloning state should probably be triggered by the
`choo.debug` command, together with tracing call-sites.

If we solve this bug, is there any other reason to keep the two modules
separate?

**Comment by timwis** [comment]
:+1: I've always wondered why they're separate. Even if we can't fix that bug, we could add an option to the constructor, ie. `app.use(require('choo-devtools')({ log: nope }))`

**Comment by s3ththompson** [comment]
Sounds good to me.

**Comment by yoshuawuyts** [comment]
Published `choo-devtools@2.0.0`.  and published & deprecated `choo-log@8.0.0` so only new installs for `choo-log` will throw a warning. Hope this good — thanks all! :sparkles:

**Comment by tgfjt** [comment]
I didn't know choo-devtools! congrats:tada:
